version: 2
jobs:
  test:
    working_directory: ~/lorengreenfield/stalefish
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:8.11.3
        command: /sbin/init
    steps:
      - checkout
      - run: export PATH="~/lorengreenfield/stalefish/node_modules/.bin:$PATH"
      - run: npm install
      - run: npm run test:lint
