version: 2
jobs:
  build:
    working_directory: ~/lorengreenfield/stalefish
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:18.12.1
    steps:
      - checkout
      - run: export PATH="~/lorengreenfield/stalefish/node_modules/.bin:$PATH"
      - run: npm install
      - run: npm run test:lint
